### ISSUE TITLE
Error in Code

### ISSUE THREAD

**Issue by saxenarohit** [aistairc/seq2seq_temporal_attention#3]
running ./example.sh --gpu 0

pickle.PickleError: can't pickle repeated message fields, convert to list first

**Comment by saxenarohit** [comment]
Also, please change `chainer.functions import caffe` to `chainer.links import caffe`
in  chainer_extract_vgg.py

**Comment by natsudalkr** [comment]
@saxenarohit Thank you very much for pointing out the issues. I have already updated the code to fix the above two errors.
